"""changr role

Revision ID: 10db924764f7
Revises: 74b9199bccfe
Create Date: 2016-10-11 15:18:53.958000

"""

# revision identifiers, used by Alembic.
revision = '10db924764f7'
down_revision = '74b9199bccfe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('admin', sa.Boolean(), server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'admin')
    ### end Alembic commands ###
