"""initianal

Revision ID: 74b9199bccfe
Revises: None
Create Date: 2016-10-11 15:15:39.802000

"""

# revision identifiers, used by Alembic.
revision = '74b9199bccfe'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cust', sa.Column('active', sa.Boolean(), server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cust', 'active')
    ### end Alembic commands ###
